version: "3.8"
services:
  app:
    container_name: my-app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/mydb
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    deploy:
      resources:
        limits:
          cpus: "6" # Allocate 16 CPU cores
          memory: 16G

    depends_on:
      - mongo
      - zipkin

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    environment:
      - JAVA_OPTS=-Xmx512m

volumes:
  mongo-data:
